import { mkdir, mkdtemp, readFile, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { buildWorkflowBundle, resolveWorkflowModulePath } from "../src/temporal/worker.js";
import {
  installRuntimeWorkflowModule,
  listRuntimeWorkflowModules,
  resolveTychonicPackageRootFromCli,
  runtimeWorkflowModulesDir,
  removeRuntimeWorkflowModule
} from "../src/temporal/workflowModules.js";

describe("Temporal bridge", () => {
  it("resolves a packaged CLI path back to the tychonic package root", async () => {
    const fixture = await makePackagedCliFixture(
      await mkdtemp(join(tmpdir(), "tychonic-temporal-cli-root-")),
      "sampleWorkflow"
    );
    await expect(resolveTychonicPackageRootFromCli(fixture.cliPath)).resolves.toBe(fixture.packageRoot);
  });

  it("loads every installed bundle through the same path", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "tychonic-temporal-workflows-"));
    const bundleAlpha = await makeBundleDir(cwd, "alphaWorkflow");
    const bundleBeta = await makeBundleDir(cwd, "betaWorkflow");
    const originalStateHome = process.env.TYCHONIC_STATE_HOME;
    process.env.TYCHONIC_STATE_HOME = join(cwd, "state");
    try {
      await installRuntimeWorkflowModule({ sourcePath: bundleAlpha });
      await installRuntimeWorkflowModule({ sourcePath: bundleBeta });

      const combinedPath = await resolveWorkflowModulePath();
      const combined = await readFile(combinedPath, "utf8");
      expect(combined).toContain("Generated by Tychonic");
      expect(combined).toContain("alphaWorkflow/workflow.mjs");
      expect(combined).toContain("betaWorkflow/workflow.mjs");

      const names = (await listRuntimeWorkflowModules()).map((m) => m.name);
      expect(names).toEqual(["alphaWorkflow", "betaWorkflow"]);

      await removeRuntimeWorkflowModule("alphaWorkflow");
      await removeRuntimeWorkflowModule("betaWorkflow");
      expect(await listRuntimeWorkflowModules()).toEqual([]);
    } finally {
      if (originalStateHome === undefined) {
        delete process.env.TYCHONIC_STATE_HOME;
      } else {
        process.env.TYCHONIC_STATE_HOME = originalStateHome;
      }
    }
  });

  it("installs a packaged bundle by its directory name", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "tychonic-temporal-current-packaged-"));
    const fixture = await makePackagedCliFixture(cwd, "packagedBundle");
    const originalStateHome = process.env.TYCHONIC_STATE_HOME;
    process.env.TYCHONIC_STATE_HOME = join(cwd, "state");
    try {
      const installed = await installRuntimeWorkflowModule({ sourcePath: fixture.bundleSourceDir });
      expect(installed.name).toBe("packagedBundle");
      expect(installed.path).toMatch(/packagedBundle$/);
    } finally {
      if (originalStateHome === undefined) {
        delete process.env.TYCHONIC_STATE_HOME;
      } else {
        process.env.TYCHONIC_STATE_HOME = originalStateHome;
      }
    }
  });

  it("rejects runtime workflow export conflicts before webpack bundling", async () => {
    // A pair of installed bundles land on disk where one exports a
    // workflow function name that matches another bundle's directory
    // name. `assertNoInstalledWorkflowExportConflicts` (called through
    // resolveWorkflowModulePath) must reject before combined-workflows.mjs
    // is generated.
    const cwd = await mkdtemp(join(tmpdir(), "tychonic-temporal-runtime-export-conflict-"));
    const originalStateHome = process.env.TYCHONIC_STATE_HOME;
    process.env.TYCHONIC_STATE_HOME = join(cwd, "state");
    const modulesDir = runtimeWorkflowModulesDir();
    const alphaDir = join(modulesDir, "alphaWorkflow");
    const betaDir = join(modulesDir, "betaWorkflow");
    await mkdir(alphaDir, { recursive: true });
    await mkdir(betaDir, { recursive: true });
    await writeFile(join(alphaDir, "workflow.mjs"), installedWorkflowSource("alphaWorkflow", "a"), "utf8");
    await writeFile(
      join(betaDir, "workflow.mjs"),
      installedWorkflowSource("betaWorkflow", "b", "export async function alphaWorkflow() { return 'b-alpha'; }"),
      "utf8"
    );
    try {
      await expect(resolveWorkflowModulePath()).rejects.toThrow(/workflow bundle export conflict/);
    } finally {
      if (originalStateHome === undefined) {
        delete process.env.TYCHONIC_STATE_HOME;
      } else {
        process.env.TYCHONIC_STATE_HOME = originalStateHome;
      }
    }
  });

  it("builds workflow bundles generated from YAML source", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "tychonic-temporal-package-state-"));
    const realStateHome = join(cwd, "real-state");
    const symlinkStateHome = join(cwd, "state-link");
    await mkdir(realStateHome, { recursive: true });
    await symlink(realStateHome, symlinkStateHome);
    const alpha = await makeBundleDir(cwd, "alphaWorkflow");
    const beta = await makeBundleDir(cwd, "betaWorkflow");
    const originalStateHome = process.env.TYCHONIC_STATE_HOME;
    process.env.TYCHONIC_STATE_HOME = symlinkStateHome;
    try {
      await installRuntimeWorkflowModule({ sourcePath: alpha });
      await installRuntimeWorkflowModule({ sourcePath: beta });
      await expect(buildWorkflowBundle()).resolves.toMatchObject({ code: expect.any(String) });
    } finally {
      if (originalStateHome === undefined) {
        delete process.env.TYCHONIC_STATE_HOME;
      } else {
        process.env.TYCHONIC_STATE_HOME = originalStateHome;
      }
    }
  }, 15_000);

  it("builds a reference example bundle without per-bundle npm install", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "tychonic-temporal-example-no-install-"));
    const sourceDir = join(process.cwd(), "examples", "workflows", "verifyOnlyWorkflow");
    const bundleDir = join(cwd, "verifyOnlyWorkflow");
    const originalStateHome = process.env.TYCHONIC_STATE_HOME;
    await mkdir(bundleDir, { recursive: true });
    await writeFile(join(bundleDir, "workflow.yaml"), await readFile(join(sourceDir, "workflow.yaml"), "utf8"), "utf8");
    await writeFile(join(bundleDir, "README.md"), await readFile(join(sourceDir, "README.md"), "utf8"), "utf8");
    process.env.TYCHONIC_STATE_HOME = join(cwd, "state");
    try {
      await installRuntimeWorkflowModule({ sourcePath: bundleDir });
      await expect(buildWorkflowBundle()).resolves.toMatchObject({ code: expect.any(String) });
    } finally {
      if (originalStateHome === undefined) {
        delete process.env.TYCHONIC_STATE_HOME;
      } else {
        process.env.TYCHONIC_STATE_HOME = originalStateHome;
      }
    }
  }, 15_000);
});

async function makePackagedCliFixture(
  root: string,
  bundleName: string
): Promise<{ packageRoot: string; cliPath: string; bundleSourceDir: string }> {
  const packageRoot = join(root, "app", "node_modules", "tychonic");
  const cliPath = join(packageRoot, "dist", "cli", "main.js");
  const bundleSourceDir = join(root, "operator-bundles", bundleName);
  await mkdir(join(packageRoot, "dist", "cli"), { recursive: true });
  await mkdir(bundleSourceDir, { recursive: true });
  await writeFile(join(packageRoot, "package.json"), JSON.stringify({ name: "tychonic" }), "utf8");
  await writeFile(cliPath, "#!/usr/bin/env node\n", "utf8");
  await writeFile(join(bundleSourceDir, "workflow.yaml"), workflowYaml(bundleName), "utf8");
  return { packageRoot, cliPath, bundleSourceDir };
}

async function makeBundleDir(
  parent: string,
  name: string
): Promise<string> {
  const dir = join(parent, name);
  await mkdir(dir, { recursive: true });
  await writeFile(join(dir, "workflow.yaml"), workflowYaml(name), "utf8");
  return dir;
}

function workflowYaml(name: string): string {
  return [
    "version: tychonic.workflow.v1",
    `name: ${name}`,
    "worktree: false",
    "max_steps: 3",
    "start: verify",
    "states:",
    "  verify:",
    "    type: verify",
    "    command: echo ok",
    "    on_pass:",
    "      finish: true",
    "    on_fail:",
    "      finish: verify failed",
    ""
  ].join("\n");
}

function installedWorkflowSource(
  exportName: string,
  tag: string,
  extra?: string
): string {
  const lines = [
    "export const defaultProfile = {",
    "  version: 'tychonic.config.v1',",
    "  states: { verify: { type: 'verify', command: 'echo ok' } }",
    "};",
    `export const workflowDefinition = { version: 'tychonic.workflow.v1', name: ${JSON.stringify(exportName)} };`,
    `export async function ${exportName}() { return ${JSON.stringify(tag)}; }`
  ];
  if (extra) lines.push(extra);
  lines.push("");
  return lines.join("\n");
}
