import { execFile } from "node:child_process";
import { cp, mkdir, mkdtemp, readFile, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { promisify } from "node:util";
import { describe, expect, it } from "vitest";
import { buildWorkflowBundle, resolveWorkflowModulePath } from "../src/temporal/worker.js";
import {
  installRuntimeWorkflowModule,
  listRuntimeWorkflowModules,
  resolveTychonicPackageRootFromCli,
  runtimeWorkflowModulesDir,
  removeRuntimeWorkflowModule
} from "../src/temporal/workflowModules.js";

const execFileAsync = promisify(execFile);

describe("Temporal bridge", () => {
  it("resolves a packaged CLI path back to the tychonic package root", async () => {
    const fixture = await makePackagedCliFixture(
      await mkdtemp(join(tmpdir(), "tychonic-temporal-cli-root-")),
      "sampleWorkflow",
      bundleSource("sampleWorkflow", "fixture")
    );
    await expect(resolveTychonicPackageRootFromCli(fixture.cliPath)).resolves.toBe(fixture.packageRoot);
  });

  it("loads every installed bundle through the same path", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "tychonic-temporal-workflows-"));
    const bundleAlpha = await makeBundleDir(cwd, "alphaWorkflow");
    const bundleBeta = await makeBundleDir(cwd, "betaWorkflow");
    const originalStateHome = process.env.TYCHONIC_STATE_HOME;
    process.env.TYCHONIC_STATE_HOME = join(cwd, "state");
    try {
      await installRuntimeWorkflowModule({ sourcePath: bundleAlpha });
      await installRuntimeWorkflowModule({ sourcePath: bundleBeta });

      const combinedPath = await resolveWorkflowModulePath();
      const combined = await readFile(combinedPath, "utf8");
      expect(combined).toContain("Generated by Tychonic");
      expect(combined).toContain("alphaWorkflow/workflow.mjs");
      expect(combined).toContain("betaWorkflow/workflow.mjs");

      const names = (await listRuntimeWorkflowModules()).map((m) => m.name);
      expect(names).toEqual(["alphaWorkflow", "betaWorkflow"]);

      await removeRuntimeWorkflowModule("alphaWorkflow");
      await removeRuntimeWorkflowModule("betaWorkflow");
      expect(await listRuntimeWorkflowModules()).toEqual([]);
    } finally {
      if (originalStateHome === undefined) {
        delete process.env.TYCHONIC_STATE_HOME;
      } else {
        process.env.TYCHONIC_STATE_HOME = originalStateHome;
      }
    }
  });

  it("installs a packaged bundle by its directory name", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "tychonic-temporal-current-packaged-"));
    const fixture = await makePackagedCliFixture(cwd, "packagedBundle", bundleSource("packagedBundle", "fixture"));
    const originalStateHome = process.env.TYCHONIC_STATE_HOME;
    process.env.TYCHONIC_STATE_HOME = join(cwd, "state");
    try {
      const installed = await installRuntimeWorkflowModule({ sourcePath: fixture.bundleSourceDir });
      expect(installed.name).toBe("packagedBundle");
      expect(installed.path).toMatch(/packagedBundle$/);
    } finally {
      if (originalStateHome === undefined) {
        delete process.env.TYCHONIC_STATE_HOME;
      } else {
        process.env.TYCHONIC_STATE_HOME = originalStateHome;
      }
    }
  });

  it("rejects install-time workflow export name conflicts with installed bundles", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "tychonic-temporal-export-conflict-"));
    const originalStateHome = process.env.TYCHONIC_STATE_HOME;
    process.env.TYCHONIC_STATE_HOME = join(cwd, "state");
    // First bundle owns the `pipelineWorkflow` name through its own
    // directory. The second bundle's workflow name is different, but it
    // also exports a `pipelineWorkflow` function: the install must be
    // refused because the combined runtime registry cannot carry two
    // `pipelineWorkflow` workflow functions.
    const first = await makeBundleDir(cwd, "pipelineWorkflow");
    const second = await makeBundleDir(cwd, "secondPipeline", {
      extraExport: "export async function pipelineWorkflow() { return 'two'; }"
    });
    try {
      await installRuntimeWorkflowModule({ sourcePath: first });
      await expect(installRuntimeWorkflowModule({ sourcePath: second })).rejects.toThrow(
        /workflow export name conflict/
      );
      expect((await listRuntimeWorkflowModules()).map((module) => module.name)).toEqual(["pipelineWorkflow"]);
    } finally {
      if (originalStateHome === undefined) {
        delete process.env.TYCHONIC_STATE_HOME;
      } else {
        process.env.TYCHONIC_STATE_HOME = originalStateHome;
      }
    }
  });

  it("rejects runtime workflow export conflicts before webpack bundling", async () => {
    // A pair of installed bundles land on disk where one exports a
    // workflow function name that matches another bundle's directory
    // name. `assertNoInstalledWorkflowExportConflicts` (called through
    // resolveWorkflowModulePath) must reject before combined-workflows.mjs
    // is generated.
    const cwd = await mkdtemp(join(tmpdir(), "tychonic-temporal-runtime-export-conflict-"));
    const originalStateHome = process.env.TYCHONIC_STATE_HOME;
    process.env.TYCHONIC_STATE_HOME = join(cwd, "state");
    const modulesDir = runtimeWorkflowModulesDir();
    const alphaDir = join(modulesDir, "alphaWorkflow");
    const betaDir = join(modulesDir, "betaWorkflow");
    await mkdir(alphaDir, { recursive: true });
    await mkdir(betaDir, { recursive: true });
    await writeFile(join(alphaDir, "workflow.mjs"), bundleSource("alphaWorkflow", "a"), "utf8");
    await writeFile(
      join(betaDir, "workflow.mjs"),
      bundleSource("betaWorkflow", "b", "export async function alphaWorkflow() { return 'b-alpha'; }"),
      "utf8"
    );
    try {
      await expect(resolveWorkflowModulePath()).rejects.toThrow(/workflow bundle export conflict/);
    } finally {
      if (originalStateHome === undefined) {
        delete process.env.TYCHONIC_STATE_HOME;
      } else {
        process.env.TYCHONIC_STATE_HOME = originalStateHome;
      }
    }
  });

  it("builds a workflow bundle with dependencies resolved from the installed bundle package", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "tychonic-temporal-package-state-"));
    const realStateHome = join(cwd, "real-state");
    const symlinkStateHome = join(cwd, "state-link");
    await mkdir(realStateHome, { recursive: true });
    await symlink(realStateHome, symlinkStateHome);
    const alpha = await makeBundleDir(cwd, "alphaWorkflow", { localDependency: true });
    const beta = await makeBundleDir(cwd, "betaWorkflow");
    const originalStateHome = process.env.TYCHONIC_STATE_HOME;
    process.env.TYCHONIC_STATE_HOME = symlinkStateHome;
    try {
      await installRuntimeWorkflowModule({ sourcePath: alpha });
      await installRuntimeWorkflowModule({ sourcePath: beta });
      await expect(buildWorkflowBundle()).resolves.toMatchObject({ code: expect.any(String) });
    } finally {
      if (originalStateHome === undefined) {
        delete process.env.TYCHONIC_STATE_HOME;
      } else {
        process.env.TYCHONIC_STATE_HOME = originalStateHome;
      }
    }
  }, 15_000);
});

async function makePackagedCliFixture(
  root: string,
  bundleName: string,
  packagedContents: string
): Promise<{ packageRoot: string; cliPath: string; bundleSourceDir: string }> {
  const packageRoot = join(root, "app", "node_modules", "tychonic");
  const cliPath = join(packageRoot, "dist", "cli", "main.js");
  const bundleSourceDir = join(root, "operator-bundles", bundleName);
  await mkdir(join(packageRoot, "dist", "cli"), { recursive: true });
  await mkdir(bundleSourceDir, { recursive: true });
  await writeFile(join(packageRoot, "package.json"), JSON.stringify({ name: "tychonic" }), "utf8");
  await writeFile(cliPath, "#!/usr/bin/env node\n", "utf8");
  await writeFile(join(bundleSourceDir, "workflow.mjs"), packagedContents, "utf8");
  return { packageRoot, cliPath, bundleSourceDir };
}

async function makeBundleDir(
  parent: string,
  name: string,
  options?: { extraExport?: string; localDependency?: boolean }
): Promise<string> {
  const dir = join(parent, name);
  await mkdir(dir, { recursive: true });
  await writeFile(
    join(dir, "workflow.mjs"),
    bundleSource(name, name, options?.extraExport, options?.localDependency),
    "utf8"
  );
  if (options?.localDependency) {
    await writeFile(
      join(dir, "package.json"),
      JSON.stringify(
        {
          name,
          private: true,
          type: "module",
          dependencies: { "@temporalio/workflow": "1.16.0", "local-workflow-helper": "1.0.0" }
        },
        null,
        2
      ),
      "utf8"
    );
    const nodeModulesDir = join(dir, "node_modules");
    const depDir = join(nodeModulesDir, "local-workflow-helper");
    await mkdir(depDir, { recursive: true });
    await writeFile(
      join(depDir, "package.json"),
      JSON.stringify({ name: "local-workflow-helper", type: "module", main: "index.js" }),
      "utf8"
    );
    await writeFile(join(depDir, "index.js"), "export const helperTag = 'local-helper';\n", "utf8");
    await copyInstalledPackageClosure("@temporalio/workflow", nodeModulesDir);
  }
  return dir;
}

async function copyInstalledPackageClosure(
  packageName: string,
  destNodeModulesDir: string,
  seen = new Set<string>()
): Promise<void> {
  if (seen.has(packageName)) return;
  seen.add(packageName);

  const sourcePackageDir = join(process.cwd(), "node_modules", packageName);
  const targetPackageDir = join(destNodeModulesDir, packageName);
  const packageJson = JSON.parse(await readFile(join(sourcePackageDir, "package.json"), "utf8")) as {
    dependencies?: Record<string, string>;
  };
  await mkdir(dirname(targetPackageDir), { recursive: true });
  await cp(sourcePackageDir, targetPackageDir, { recursive: true });

  for (const dependencyName of Object.keys(packageJson.dependencies ?? {}).sort()) {
    await copyInstalledPackageClosure(dependencyName, destNodeModulesDir, seen);
  }
}

function bundleSource(exportName: string, tag: string, extra?: string, localDependency = false): string {
  const lines = [
    ...(localDependency ? ['import { helperTag } from "local-workflow-helper";'] : []),
    "export const defaultProfile = {",
    "  version: 'tychonic.config.v1',",
    "  states: { verify: { type: 'verify', command: 'echo ok' } }",
    "};",
    `export async function ${exportName}() { return ${localDependency ? "helperTag" : JSON.stringify(tag)}; }`
  ];
  if (extra) lines.push(extra);
  lines.push("");
  return lines.join("\n");
}
