import { execFile } from "node:child_process";
import { mkdir, mkdtemp, readFile, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import { describe, expect, it } from "vitest";
import { runSimpleWorkflowActivity } from "../src/activities/index.js";
import { buildWorkflowBundle, resolveWorkflowModulePath } from "../src/temporal/worker.js";
import {
  installRuntimeWorkflowModule,
  listRuntimeWorkflowModules,
  packagedWorkflowBundleRoot,
  resolveTychonicPackageRootFromCli,
  runtimeWorkflowModulesDir,
  removeRuntimeWorkflowModule
} from "../src/temporal/workflowModules.js";

const execFileAsync = promisify(execFile);

describe("Temporal bridge", () => {
  it("resolves the packaged workflow bundle root", () => {
    expect(packagedWorkflowBundleRoot()).toMatch(/workflow-bundles$/);
  });

  it("resolves a packaged CLI path back to the tychonic package root", async () => {
    const fixture = await makePackagedCliFixture(
      await mkdtemp(join(tmpdir(), "tychonic-temporal-cli-root-")),
      "selfRepairWorkflow",
      bundleSource("selfRepairWorkflow", "fixture")
    );
    await expect(resolveTychonicPackageRootFromCli(fixture.cliPath)).resolves.toBe(fixture.packageRoot);
  });

  it("loads every installed bundle through the same path", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "tychonic-temporal-workflows-"));
    const bundleAlpha = await makeBundleDir(cwd, "alphaWorkflow");
    const bundleBeta = await makeBundleDir(cwd, "betaWorkflow");
    const originalStateHome = process.env.TYCHONIC_STATE_HOME;
    process.env.TYCHONIC_STATE_HOME = join(cwd, "state");
    try {
      await installRuntimeWorkflowModule({ sourcePath: bundleAlpha });
      await installRuntimeWorkflowModule({ sourcePath: bundleBeta });

      const combinedPath = await resolveWorkflowModulePath();
      const combined = await readFile(combinedPath, "utf8");
      expect(combined).toContain("Generated by Tychonic");
      expect(combined).toContain("alphaWorkflow/workflow.mjs");
      expect(combined).toContain("betaWorkflow/workflow.mjs");

      const names = (await listRuntimeWorkflowModules()).map((m) => m.name);
      expect(names).toEqual(["alphaWorkflow", "betaWorkflow"]);

      await removeRuntimeWorkflowModule("alphaWorkflow");
      await removeRuntimeWorkflowModule("betaWorkflow");
      expect(await listRuntimeWorkflowModules()).toEqual([]);
    } finally {
      if (originalStateHome === undefined) {
        delete process.env.TYCHONIC_STATE_HOME;
      } else {
        process.env.TYCHONIC_STATE_HOME = originalStateHome;
      }
    }
  });

  it("installs a packaged bundle by its directory name", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "tychonic-temporal-current-packaged-"));
    const fixture = await makePackagedCliFixture(cwd, "packagedBundle", bundleSource("packagedBundle", "fixture"));
    const originalStateHome = process.env.TYCHONIC_STATE_HOME;
    process.env.TYCHONIC_STATE_HOME = join(cwd, "state");
    try {
      const installed = await installRuntimeWorkflowModule({ sourcePath: fixture.packagedBundleDir });
      expect(installed.name).toBe("packagedBundle");
      expect(installed.path).toMatch(/packagedBundle$/);
    } finally {
      if (originalStateHome === undefined) {
        delete process.env.TYCHONIC_STATE_HOME;
      } else {
        process.env.TYCHONIC_STATE_HOME = originalStateHome;
      }
    }
  });

  it("rejects install-time workflow export name conflicts with installed bundles", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "tychonic-temporal-export-conflict-"));
    const originalStateHome = process.env.TYCHONIC_STATE_HOME;
    process.env.TYCHONIC_STATE_HOME = join(cwd, "state");
    // First bundle owns the `pipelineWorkflow` name through its own
    // directory. The second bundle's workflow name is different, but it
    // also exports a `pipelineWorkflow` function: the install must be
    // refused because the combined runtime registry cannot carry two
    // `pipelineWorkflow` workflow functions.
    const first = await makeBundleDir(cwd, "pipelineWorkflow");
    const second = await makeBundleDir(cwd, "secondPipeline", {
      extraExport: "export async function pipelineWorkflow() { return 'two'; }"
    });
    try {
      await installRuntimeWorkflowModule({ sourcePath: first });
      await expect(installRuntimeWorkflowModule({ sourcePath: second })).rejects.toThrow(
        /workflow export name conflict/
      );
      expect((await listRuntimeWorkflowModules()).map((module) => module.name)).toEqual(["pipelineWorkflow"]);
    } finally {
      if (originalStateHome === undefined) {
        delete process.env.TYCHONIC_STATE_HOME;
      } else {
        process.env.TYCHONIC_STATE_HOME = originalStateHome;
      }
    }
  });

  it("rejects runtime workflow export conflicts before webpack bundling", async () => {
    // A pair of installed bundles land on disk where one exports a
    // workflow function name that matches another bundle's directory
    // name. `assertNoInstalledWorkflowExportConflicts` (called through
    // resolveWorkflowModulePath) must reject before combined-workflows.mjs
    // is generated.
    const cwd = await mkdtemp(join(tmpdir(), "tychonic-temporal-runtime-export-conflict-"));
    const originalStateHome = process.env.TYCHONIC_STATE_HOME;
    process.env.TYCHONIC_STATE_HOME = join(cwd, "state");
    const modulesDir = runtimeWorkflowModulesDir();
    const alphaDir = join(modulesDir, "alphaWorkflow");
    const betaDir = join(modulesDir, "betaWorkflow");
    await mkdir(alphaDir, { recursive: true });
    await mkdir(betaDir, { recursive: true });
    await writeFile(join(alphaDir, "workflow.mjs"), bundleSource("alphaWorkflow", "a"), "utf8");
    await writeFile(join(alphaDir, "config.yaml"), simpleVerifyConfig(), "utf8");
    await writeFile(
      join(betaDir, "workflow.mjs"),
      bundleSource("betaWorkflow", "b", "export async function alphaWorkflow() { return 'b-alpha'; }"),
      "utf8"
    );
    await writeFile(join(betaDir, "config.yaml"), simpleVerifyConfig(), "utf8");
    try {
      await expect(resolveWorkflowModulePath()).rejects.toThrow(/workflow bundle export conflict/);
    } finally {
      if (originalStateHome === undefined) {
        delete process.env.TYCHONIC_STATE_HOME;
      } else {
        process.env.TYCHONIC_STATE_HOME = originalStateHome;
      }
    }
  });

  it("builds a workflow bundle when TYCHONIC_STATE_HOME points through a symlinked temp path", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "tychonic-temporal-symlink-state-"));
    const realStateHome = join(cwd, "real-state");
    const symlinkStateHome = join(cwd, "state-link");
    await mkdir(realStateHome, { recursive: true });
    await symlink(realStateHome, symlinkStateHome);
    const alpha = await makeBundleDir(cwd, "alphaWorkflow");
    const beta = await makeBundleDir(cwd, "betaWorkflow");
    const originalStateHome = process.env.TYCHONIC_STATE_HOME;
    process.env.TYCHONIC_STATE_HOME = symlinkStateHome;
    try {
      await installRuntimeWorkflowModule({ sourcePath: alpha });
      await installRuntimeWorkflowModule({ sourcePath: beta });
      await expect(buildWorkflowBundle()).resolves.toMatchObject({ code: expect.any(String) });
    } finally {
      if (originalStateHome === undefined) {
        delete process.env.TYCHONIC_STATE_HOME;
      } else {
        process.env.TYCHONIC_STATE_HOME = originalStateHome;
      }
    }
  });


  it("runs simple_workflow through Temporal activity result without persisting run.json", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "tychonic-temporal-fix-"));
    await execFileAsync("git", ["init"], { cwd });
    await writeFile(join(cwd, "seed.txt"), "seed\n", "utf8");

    const result = await runSimpleWorkflowActivity({
      cwd,
      runId: "run_temporal_fix",
      goal: "create delegated marker file",
      command: "node -e \"require('fs').writeFileSync('delegated.txt', 'ok')\"",
      verifyCommand:
        "node -e \"process.exit(require('fs').existsSync('delegated.txt') ? 0 : 1)\"",
      commandTimeoutMs: 10_000
    });

    expect(result).toMatchObject({
      runId: "run_temporal_fix",
      status: "succeeded",
      run: {
        id: "run_temporal_fix",
        template: "simple_workflow",
        status: "succeeded"
      },
      artifactRoot: join(cwd, ".tychonic", "runs", "run_temporal_fix")
    });
    await expect(readFile(join(cwd, ".tychonic", "runs", "run_temporal_fix", "run.json"), "utf8")).rejects.toThrow();
  });
});

async function makePackagedCliFixture(
  root: string,
  bundleName: string,
  packagedContents: string
): Promise<{ packageRoot: string; cliPath: string; packagedBundleDir: string }> {
  const packageRoot = join(root, "app", "node_modules", "tychonic");
  const cliPath = join(packageRoot, "dist", "cli", "main.js");
  const packagedBundleDir = join(packageRoot, "dist", "workflow-bundles", bundleName);
  await mkdir(join(packageRoot, "dist", "cli"), { recursive: true });
  await mkdir(packagedBundleDir, { recursive: true });
  await writeFile(join(packageRoot, "package.json"), JSON.stringify({ name: "tychonic" }), "utf8");
  await writeFile(cliPath, "#!/usr/bin/env node\n", "utf8");
  await writeFile(join(packagedBundleDir, "workflow.mjs"), packagedContents, "utf8");
  await writeFile(join(packagedBundleDir, "config.yaml"), simpleVerifyConfig(), "utf8");
  return { packageRoot, cliPath, packagedBundleDir };
}

async function makeBundleDir(
  parent: string,
  name: string,
  options?: { extraExport?: string }
): Promise<string> {
  const dir = join(parent, name);
  await mkdir(dir, { recursive: true });
  await writeFile(
    join(dir, "workflow.mjs"),
    bundleSource(name, name, options?.extraExport),
    "utf8"
  );
  await writeFile(join(dir, "config.yaml"), simpleVerifyConfig(), "utf8");
  return dir;
}

function bundleSource(exportName: string, tag: string, extra?: string): string {
  const lines = [
    "export const requires = { states: [ { name: 'verify', type: 'verify' } ] };",
    `export async function ${exportName}() { return ${JSON.stringify(tag)}; }`
  ];
  if (extra) lines.push(extra);
  lines.push("");
  return lines.join("\n");
}

function simpleVerifyConfig(): string {
  return "version: tychonic.config.v1\nstates:\n  verify:\n    type: verify\n    command: echo ok\n";
}
