// Generated by ui-lab emit-accent-runtime. Do not hand-edit.
// Source of truth: ~/.agents/skills/ui-lab/tools/ui_lab_cli/tokens_data.py
//
// Fixed accent runtime. install-stack initializes UI_LAB_ACCENT_DEFAULT.
// Agents must not create picker UI or ask which preset to use.
// applyUiLabAccent() is only a wiring API for explicitly requested controls.
//
// Mechanism: this module only toggles the [data-ui-lab-accent] attribute
// on document.documentElement and persists the preset id. CSS rules emitted
// by ui-lab emit-tokens own the actual values for each preset × mode
// combination, so light/dark switching via .dark class or media query
// keeps working without re-applying inline styles.

export type UiLabAccentPresetId = 'slate-blue' | 'ocean' | 'emerald' | 'amber' | 'rose' | 'violet' | 'crimson' | 'graphite'

export interface UiLabAccentPaletteTokens {
  primary: string
  primaryForeground: string
  accentHover: string
  accentMuted: string
}

export interface UiLabAccentPreset {
  id: UiLabAccentPresetId
  label: string
  light: UiLabAccentPaletteTokens
  dark: UiLabAccentPaletteTokens
}

export const UI_LAB_ACCENT_PRESETS: readonly UiLabAccentPreset[] = [
  { id: 'slate-blue', label: 'Slate Blue', light: { primary: 'oklch(0.55 0.22 250)', primaryForeground: 'oklch(0.98 0.001 264)', accentHover: 'oklch(0.60 0.24 250)', accentMuted: 'oklch(0.92 0.035 250)' }, dark: { primary: 'oklch(0.65 0.20 250)', primaryForeground: 'oklch(0.98 0.001 264)', accentHover: 'oklch(0.70 0.22 250)', accentMuted: 'oklch(0.30 0.08 250)' } },
  { id: 'ocean', label: 'Ocean', light: { primary: 'oklch(0.55 0.16 220)', primaryForeground: 'oklch(0.98 0.001 264)', accentHover: 'oklch(0.60 0.18 220)', accentMuted: 'oklch(0.92 0.035 220)' }, dark: { primary: 'oklch(0.68 0.14 220)', primaryForeground: 'oklch(0.98 0.001 264)', accentHover: 'oklch(0.72 0.16 220)', accentMuted: 'oklch(0.32 0.08 220)' } },
  { id: 'emerald', label: 'Emerald', light: { primary: 'oklch(0.55 0.18 155)', primaryForeground: 'oklch(0.98 0.001 264)', accentHover: 'oklch(0.60 0.20 155)', accentMuted: 'oklch(0.93 0.040 155)' }, dark: { primary: 'oklch(0.68 0.16 155)', primaryForeground: 'oklch(0.18 0.01 155)', accentHover: 'oklch(0.72 0.18 155)', accentMuted: 'oklch(0.30 0.08 155)' } },
  { id: 'amber', label: 'Amber', light: { primary: 'oklch(0.65 0.18 75)', primaryForeground: 'oklch(0.18 0.01 75)', accentHover: 'oklch(0.70 0.20 75)', accentMuted: 'oklch(0.93 0.045 75)' }, dark: { primary: 'oklch(0.74 0.16 75)', primaryForeground: 'oklch(0.18 0.01 75)', accentHover: 'oklch(0.78 0.18 75)', accentMuted: 'oklch(0.34 0.08 75)' } },
  { id: 'rose', label: 'Rose', light: { primary: 'oklch(0.55 0.20 15)', primaryForeground: 'oklch(0.98 0.001 264)', accentHover: 'oklch(0.60 0.22 15)', accentMuted: 'oklch(0.92 0.040 15)' }, dark: { primary: 'oklch(0.66 0.18 15)', primaryForeground: 'oklch(0.98 0.001 264)', accentHover: 'oklch(0.70 0.20 15)', accentMuted: 'oklch(0.32 0.10 15)' } },
  { id: 'violet', label: 'Violet', light: { primary: 'oklch(0.55 0.22 290)', primaryForeground: 'oklch(0.98 0.001 264)', accentHover: 'oklch(0.60 0.24 290)', accentMuted: 'oklch(0.92 0.035 290)' }, dark: { primary: 'oklch(0.66 0.20 290)', primaryForeground: 'oklch(0.98 0.001 264)', accentHover: 'oklch(0.70 0.22 290)', accentMuted: 'oklch(0.32 0.10 290)' } },
  { id: 'crimson', label: 'Crimson', light: { primary: 'oklch(0.52 0.22 25)', primaryForeground: 'oklch(0.98 0.001 264)', accentHover: 'oklch(0.57 0.24 25)', accentMuted: 'oklch(0.92 0.040 25)' }, dark: { primary: 'oklch(0.62 0.20 25)', primaryForeground: 'oklch(0.98 0.001 264)', accentHover: 'oklch(0.66 0.22 25)', accentMuted: 'oklch(0.30 0.10 25)' } },
  { id: 'graphite', label: 'Graphite', light: { primary: 'oklch(0.30 0.01 264)', primaryForeground: 'oklch(0.98 0.001 264)', accentHover: 'oklch(0.36 0.01 264)', accentMuted: 'oklch(0.92 0.005 264)' }, dark: { primary: 'oklch(0.85 0.005 264)', primaryForeground: 'oklch(0.18 0.01 264)', accentHover: 'oklch(0.90 0.005 264)', accentMuted: 'oklch(0.32 0.01 264)' } },
] as const

export const UI_LAB_ACCENT_DEFAULT: UiLabAccentPresetId = 'slate-blue'

const STORAGE_KEY = 'ui-lab.accent'

function isUiLabAccentPresetId(value: unknown): value is UiLabAccentPresetId {
  return typeof value === 'string'
    && UI_LAB_ACCENT_PRESETS.some(p => p.id === value)
}

export function applyUiLabAccent(presetId: UiLabAccentPresetId): void {
  if (typeof document === 'undefined') return
  document.documentElement.dataset.uiLabAccent = presetId
  try {
    window.localStorage.setItem(STORAGE_KEY, presetId)
  } catch {
    /* storage may be disabled; the data-attribute is already set */
  }
}

export function readPersistedUiLabAccent(): UiLabAccentPresetId | null {
  if (typeof window === 'undefined') return null
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY)
    return isUiLabAccentPresetId(raw) ? raw : null
  } catch {
    return null
  }
}

export function initUiLabAccent(): void {
  applyUiLabAccent(readPersistedUiLabAccent() ?? UI_LAB_ACCENT_DEFAULT)
}
