// Generated by ui-lab emit-style-contract. Do not hand-edit.
export const uiLabAccent = {
  primaryAction: 'bg-primary text-primary-foreground',
  primaryActionLabel: 'text-primary-foreground',
  selectedSurface: 'bg-[var(--accent-muted)] text-primary',
  userBubble: '!bg-[var(--accent-muted)] !text-foreground',
  statusChip: 'bg-[var(--accent-muted)] text-primary',
  navSelected: '!bg-[var(--accent-muted)] !font-semibold !text-primary hover:!bg-[var(--accent-muted)] hover:!text-primary',
  activeMarker: 'bg-primary',
  brandMark: 'bg-primary',
  inlineLink: 'text-primary hover:text-primary/80',
  pickerActive: 'ring-2 ring-primary',
} as const

export type UiLabAccentSlot = keyof typeof uiLabAccent
